package net.luck.narutoaddon.OtherCode.akatsuki.mission;

import net.luck.narutoaddon.OtherCode.quest.npc.NpcConfig;
import net.luck.narutoaddon.OtherCode.quest.npc.NpcConfigRegistry;

public class AkatsukiMissionNpcConfigs {
   public static void init() {
      initDailyTargets();
      initWeeklyBosses();
   }

   private static void initDailyTargets() {
      NpcConfigRegistry.register(NpcConfig.builder("ak_patrol_grunt", "inftsukaddon:akatsukimissionnpc").displayName("ANBU Patrol").texture("inftsukaddon", "textures/leaf1.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)30000.0F).attackDamage((double)14.0F).armor((double)7.0F).movementSpeed(0.4).combatTier(4).combatStyle("SHADOW").natureType(2).hasRangedAttack(true).knockbackImmune(true).rageThreshold(0.3F).rageDamageMultiplier(1.3F).rageSpeedMultiplier(1.2F).themeColor(-13408717).accentColor(-15060198).trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_patrol_captain", "inftsukaddon:akatsukimissionnpc").displayName("ANBU Captain").texture("inftsukaddon", "textures/the_shadow.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)36000.0F).attackDamage((double)16.5F).armor((double)8.0F).movementSpeed(0.42).combatTier(4).combatStyle("SHADOW").natureType(1).hasRangedAttack(true).knockbackImmune(true).rageThreshold(0.28F).rageDamageMultiplier(1.35F).rageSpeedMultiplier(1.25F).themeColor(-10075136).accentColor(-13426176).trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_leaf_anbu", "inftsukaddon:akatsukimissionnpc").displayName("Leaf ANBU Commander").texture("inftsukaddon", "textures/leaf3.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)40000.0F).attackDamage((double)18.0F).armor((double)9.0F).movementSpeed(0.43).combatTier(4).combatStyle("SHADOW").natureType(1).hasRangedAttack(true).knockbackImmune(true).rageThreshold(0.25F).rageDamageMultiplier(1.4F).rageSpeedMultiplier(1.3F).themeColor(-14527198).accentColor(-15650031).weaponItemId("narutomod:anbu_sword").trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_sand_guard", "inftsukaddon:akatsukimissionnpc").displayName("Sand ANBU Elite").texture("inftsukaddon", "textures/sand3.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)34000.0F).attackDamage((double)16.0F).armor((double)7.0F).movementSpeed(0.44).combatTier(4).combatStyle("FERAL").natureType(2).hasRangedAttack(true).knockbackImmune(true).rageThreshold(0.3F).rageDamageMultiplier(1.35F).rageSpeedMultiplier(1.3F).themeColor(-5601229).accentColor(-11189231).trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_mist_hunter", "inftsukaddon:akatsukimissionnpc").displayName("Mist Hunter-Nin Captain").texture("inftsukaddon", "textures/zabuza.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)42000.0F).attackDamage((double)20.0F).armor((double)8.0F).movementSpeed(0.42).combatTier(4).combatStyle("FERAL").natureType(3).hasRangedAttack(false).knockbackImmune(true).rageThreshold(0.28F).rageDamageMultiplier(1.4F).rageSpeedMultiplier(1.3F).themeColor(-14531448).accentColor(-15654332).hasWaterDragon(true).trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_cloud_sentinel", "inftsukaddon:akatsukimissionnpc").displayName("Cloud ANBU Sentinel").texture("inftsukaddon", "textures/cloud2.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)38000.0F).attackDamage((double)17.0F).armor((double)8.0F).movementSpeed(0.43).combatTier(4).combatStyle("STANDARD").natureType(4).hasRangedAttack(true).knockbackImmune(true).rageThreshold(0.3F).rageDamageMultiplier(1.35F).rageSpeedMultiplier(1.25F).themeColor(-12303190).accentColor(-14540203).trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_stone_guard", "inftsukaddon:akatsukimissionnpc").displayName("Stone ANBU Vanguard").texture("inftsukaddon", "textures/stone2.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)45000.0F).attackDamage((double)15.0F).armor((double)14.0F).movementSpeed(0.38).combatTier(4).combatStyle("STANDARD").natureType(1).hasRangedAttack(false).knockbackImmune(true).rageThreshold(0.25F).rageDamageMultiplier(1.4F).rageSpeedMultiplier(1.2F).themeColor(-7838140).accentColor(-12307678).renderScale(1.2F).trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_bounty_hunter", "inftsukaddon:akatsukimissionnpc").displayName("Elite Bounty Hunter").texture("inftsukaddon", "textures/assassin1.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)33000.0F).attackDamage((double)17.0F).armor((double)6.0F).movementSpeed(0.45).combatTier(4).combatStyle("FERAL").natureType(1).hasRangedAttack(false).knockbackImmune(true).rageThreshold(0.3F).rageDamageMultiplier(1.4F).rageSpeedMultiplier(1.35F).themeColor(-7855582).accentColor(-12316399).trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_bounty_elite", "inftsukaddon:akatsukimissionnpc").displayName("ANBU Bounty Captain").texture("inftsukaddon", "textures/assassin2.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)40000.0F).attackDamage((double)19.0F).armor((double)8.0F).movementSpeed(0.44).combatTier(4).combatStyle("SHADOW").natureType(4).hasRangedAttack(true).knockbackImmune(true).rageThreshold(0.25F).rageDamageMultiplier(1.45F).rageSpeedMultiplier(1.3F).themeColor(-10092442).accentColor(-13434829).trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_rain_agent", "inftsukaddon:akatsukimissionnpc").displayName("Rain Black Ops Agent").texture("inftsukaddon", "textures/rain_clan_leader.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)35000.0F).attackDamage((double)16.0F).armor((double)7.0F).movementSpeed(0.42).combatTier(4).combatStyle("SHADOW").natureType(3).hasRangedAttack(true).knockbackImmune(true).rageThreshold(0.3F).rageDamageMultiplier(1.35F).rageSpeedMultiplier(1.25F).themeColor(-13413001).accentColor(-15062467).trueDamageSplit(0.6F).build());
   }

   private static void initWeeklyBosses() {
      NpcConfigRegistry.register(NpcConfig.builder("ak_anbu_captain", "inftsukaddon:itachistyle").displayName("ANBU Black Ops Commander").texture("inftsukaddon", "textures/the_shadow.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)50000.0F).attackDamage((double)22.0F).armor((double)10.0F).movementSpeed(0.44).combatTier(4).combatStyle("ITACHI").natureType(1).hasRangedAttack(true).knockbackImmune(true).rageThreshold(0.25F).rageDamageMultiplier(1.45F).rageSpeedMultiplier(1.35F).themeColor(-10079488).accentColor(-13430528).renderScale(1.2F).trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_jinchuriki_guard", "inftsukaddon:questnpc1").displayName("Jinchuriki Guardian").texture("inftsukaddon", "textures/cloud3.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)60000.0F).attackDamage((double)26.0F).armor((double)12.0F).movementSpeed(0.46).combatTier(4).combatStyle("FERAL").natureType(4).hasRangedAttack(true).knockbackImmune(true).rageThreshold(0.2F).rageDamageMultiplier(1.5F).rageSpeedMultiplier(1.4F).themeColor(-7838208).accentColor(-12307712).renderScale(1.3F).trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_village_commander", "inftsukaddon:kakuzustyle").displayName("Kage Guard Commander").texture("inftsukaddon", "textures/grassshinobisarmored.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)55000.0F).attackDamage((double)20.0F).armor((double)14.0F).movementSpeed(0.4).combatTier(4).combatStyle("KAKUZU").natureType(1).hasRangedAttack(true).knockbackImmune(true).rageThreshold(0.25F).rageDamageMultiplier(1.4F).rageSpeedMultiplier(1.25F).themeColor(-14514142).accentColor(-15645679).renderScale(1.3F).trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_hunter_captain", "inftsukaddon:shadowboss").displayName("Hunter Division Captain").texture("inftsukaddon", "textures/mist1.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)48000.0F).attackDamage((double)22.0F).armor((double)9.0F).movementSpeed(0.46).combatTier(4).combatStyle("SHADOW").natureType(3).hasRangedAttack(true).knockbackImmune(true).rageThreshold(0.25F).rageDamageMultiplier(1.45F).rageSpeedMultiplier(1.35F).themeColor(-14531482).accentColor(-15654349).hasHiddenMist(true).trueDamageSplit(0.6F).build());
      NpcConfigRegistry.register(NpcConfig.builder("ak_fortress_lord", "inftsukaddon:kimimaroboss").displayName("Fortress Lord").texture("inftsukaddon", "textures/stone3.png").behavior(NpcConfig.Behavior.HOSTILE).maxHealth((double)65000.0F).attackDamage((double)28.0F).armor((double)14.0F).movementSpeed(0.42).combatTier(4).combatStyle("KIMIMARO").natureType(1).hasRangedAttack(false).knockbackImmune(true).rageThreshold(0.2F).rageDamageMultiplier(1.5F).rageSpeedMultiplier(1.4F).themeColor(-7851264).accentColor(-12316416).renderScale(1.3F).weaponItemId("narutomod:bone_sword").trueDamageSplit(0.6F).build());
   }
}
