package net.luck.narutoaddon.OtherCode.quest.core;

import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

import java.util.*;

public class MissionTemplate {
   private static final Map<TemplateId, MissionTemplate> TEMPLATES = new HashMap();
   public final TemplateId id;
   public final String baseName;
   public final Map<VillageHelper.Village, String> villageDescriptions;
   public final String genericDescription;
   public final StepTemplate[] steps;
   private static final int MAP_BOUND = 6000;

   private MissionTemplate(TemplateId id, String baseName, Map<VillageHelper.Village, String> villageDescriptions, String genericDescription, StepTemplate[] steps) {
      this.id = id;
      this.baseName = baseName;
      this.villageDescriptions = villageDescriptions;
      this.genericDescription = genericDescription;
      this.steps = steps;
   }

   public List<GeneratedStepData> generateSteps(BlockPos mainPosition, VillageHelper.Village village, Random random, World world) {
      List<GeneratedStepData> result = new ArrayList();
      BlockPos currentPos = mainPosition;

      for(StepTemplate st : this.steps) {
         BlockPos stepPos;
         if (st.nearVillage && village != VillageHelper.Village.UNKNOWN) {
            BlockPos villageCenter = new BlockPos(village.centerX, 64, village.centerZ);
            stepPos = offsetPosition(villageCenter, 50, 200, random, world);
         } else if (st.offsetMinBlocks <= 0 && st.offsetMaxBlocks <= 0) {
            stepPos = currentPos;
         } else {
            stepPos = offsetPosition(currentPos, st.offsetMinBlocks, st.offsetMaxBlocks, random, world);
         }

         String desc = st.descriptionTemplate.replace("{terrain}", village.terrainName).replace("{land}", village.landName);
         switch (st.type) {
            case TRAVEL:
               result.add(GeneratedStepData.travel(desc, stepPos));
               break;
            case COMBAT:
               String[] enemies = pickEnemies(st.enemyPool, st.enemyCountMin, st.enemyCountMax, random);
               result.add(GeneratedStepData.combat(desc, stepPos, enemies));
               break;
            case DIALOG:
               result.add(GeneratedStepData.dialog(desc, stepPos, "Village Contact", st.dialogLineTemplate, st.dialogResponseTemplate, st.dialogNpcConfigId));
               break;
            default:
               result.add(GeneratedStepData.travel(desc, stepPos));
         }

         currentPos = stepPos;
      }

      return result;
   }

   public String getDescription(VillageHelper.Village village) {
      if (this.genericDescription != null) {
         return this.genericDescription;
      } else {
         String desc = (String)this.villageDescriptions.get(village);
         if (desc == null) {
            desc = (String)this.villageDescriptions.get(VillageHelper.Village.UNKNOWN);
         }

         return desc != null ? desc : "Complete the mission objectives.";
      }
   }

   private static String[] pickEnemies(String[] pool, int min, int max, Random random) {
      int count = min + random.nextInt(max - min + 1);
      String[] result = new String[count];

      for(int i = 0; i < count; ++i) {
         result[i] = pool[random.nextInt(pool.length)];
      }

      return result;
   }

   private static BlockPos offsetPosition(BlockPos base, int minDist, int maxDist, Random random, World world) {
      TerrainCache terrain = world != null ? TerrainCache.get(world) : null;
      BlockPos result = null;

      for(int attempt = 0; attempt < 10; ++attempt) {
         double angle = random.nextDouble() * (double)2.0F * Math.PI;
         int dist = minDist + random.nextInt(maxDist - minDist + 1);
         int x = base.getX() + (int)(Math.cos(angle) * (double)dist);
         int z = base.getZ() + (int)(Math.sin(angle) * (double)dist);
         x = Math.max(-6000, Math.min(6000, x));
         z = Math.max(-6000, Math.min(6000, z));
         result = new BlockPos(x, 64, z);
         if (terrain == null || !terrain.isWater(world, x, z)) {
            return result;
         }
      }

      return result;
   }

   public static void init() {
      TEMPLATES.clear();
      registerTemplate(new MissionTemplate(TemplateId.DAILY_D_PATROL, "Perimeter Patrol", villageDescs("Scouts report movement along the treeline roads south of Konoha. The Will of Fire demands we protect every citizen on those roads. Patrol and deal with the threat.", "Caravan runners report armed men lurking near the dune corridors west of Sunagakure. The desert claims the weak -- make sure it claims them.", "Blood Mist protocol. Armed strangers spotted near the harbor docks. No survivors. Sweep the area.", "Tsuchikage's directive: suspicious figures reported near the mountain quarry paths. Patrol the route and secure it. No excuses.", "Kumogakure's supply runners encountered hostiles on the highland ridgeline. Our strength will not be questioned -- clear them out.", "Sensor array flagged movement on the wetland bridges. Armed men, not ours. Remove the obstruction before they map our infrastructure.", "Bandits spotted near the perimeter. Patrol and eliminate."), (String)null, new StepTemplate[]{StepTemplate.travel("Follow the {terrain} road to the patrol sector."), StepTemplate.combat("Armed figures ahead -- drive them off before they dig in.", new String[]{"d_bandit_1", "d_bandit_2"}, 2, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_D_GATEGUARD, "Gate Watch", villageDescs("A group of bandits was spotted approaching Konoha's outer gates along the forest road. The village must never be threatened. Intercept them.", "Raiders are massing near the canyon entrance to Sunagakure. The sand walls hold -- but only if we hold the pass. Defend it.", "Smugglers are using the fog cover to breach the harbor checkpoint. Blood Mist standing order: no one passes without clearance. Stop them.", "Intruders detected at the gorge pass into Iwagakure. The Tsuchikage's orders are absolute -- nothing gets through. Defend the chokepoint.", "Armed bandits scaling the cliffs toward Kumogakure's lower gates. The pride of the Cloud will not tolerate this. Put them down.", "Thugs forcing their way through Amegakure's drainage tunnels. Security breach -- seal the entry point. Eliminate all intruders.", "Bandits approaching the village gates. Intercept and eliminate."), (String)null, new StepTemplate[]{StepTemplate.travel("Report to the gate outpost near {terrain}."), StepTemplate.combat("They are pushing toward the gates. Cut them off here.", new String[]{"d_bandit_1", "d_bandit_1", "d_bandit_2", "d_bandit_3"}, 3, 4)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_D_GENINHUNT, "Rogue Ninja Sighting", villageDescs("A rogue genin was spotted stealing supplies from a Konoha outpost on the forest road. They dishonor the Will of Fire. Track them down.", "An ex-Sand genin has been raiding oasis camps along the dune corridor. The desert will be their grave. Locate and eliminate.", "A deserter from the academy was seen near the reef caves on the eastern shore. Mist does not forgive desertion. End them.", "A rogue ninja has been sabotaging mining equipment in the upper passes. Find them. The Tsuchikage does not tolerate disruption.", "A missing-nin was spotted near the thunder plateau. Kumogakure's reach is absolute. Hunt them down.", "A rogue ninja is extorting villagers in the outer marshlands. Sensor data confirms one target. Eliminate the breach.", "A rogue ninja has been spotted nearby. Track them down."), (String)null, new StepTemplate[]{StepTemplate.travel("Follow the trail through {terrain} to the rogue's last known position."), StepTemplate.combat("Fresh tracks. The rogue is close -- end the threat.", new String[]{"d_rogue_genin_1", "d_rogue_genin_2", "d_rogue_genin_lightning"}, 1, 2)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_D_CAMPRAID, "Bandit Camp", villageDescs("Intel suggests bandits have set up camp in the dense forests outside Konoha. For the safety of Fire Country's people, raid and dismantle it.", "A bandit camp was discovered behind the sand dunes near a dried oasis. They have been preying on caravans. Destroy it before the next sandstorm gives them cover.", "Pirates have established a hideout in a sea cave along the fog-shrouded coast. Flush them out. Leave nothing standing.", "Bandits are holed up in an abandoned mine shaft in the lower mountains. Tsuchikage's directive: clear the tunnels. Our miners need that route.", "Highland raiders have a camp in a clifftop cave overlooking the trade road. Storm it. Kumogakure will not tolerate parasites on our supply lines.", "Armed thugs built a camp on raised ground in the outer marshes. Sensor grid flagged them two days ago. Tear it down before they establish a foothold.", "A bandit camp has been discovered. Clear it out."), (String)null, new StepTemplate[]{StepTemplate.travel("Smoke rising from the {terrain} ahead. The camp is close."), StepTemplate.combat("The camp is right here. Clear them out before they scatter.", new String[]{"d_bandit_1", "d_bandit_2", "d_bandit_3"}, 3, 4)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_D_BOUNTY, "Minor Bounty Target", villageDescs("A wanted mercenary was last seen on the forest roads through Fire Country. Protecting our people means collecting every bounty. Find them.", "A bounty has been placed on a mercenary terrorizing desert caravans near the canyon passes. The desert claims the weak -- help it along.", "A mercenary with a small bounty is hiding along the fog-shrouded coast. Blood Mist protocol: bring them in dead.", "A hired blade operating in the mountain passes near the ore routes. Tsuchikage's bounty board -- yours if you can take them.", "A mercenary has been ambushing traders on the highland roads. Kumogakure's bounty authorized. Show them our strength.", "A wanted cutthroat last spotted near the flooded ruins in the outer canal district. Bounty confirmed. Eliminate.", "A bounty has been posted for a mercenary in the area. Collect it."), (String)null, new StepTemplate[]{StepTemplate.travel("Follow the bounty trail through {terrain}."), StepTemplate.combat("Target sighted. A hired blade -- armed and dangerous. Put them down.", new String[]{"d_mercenary_1"}, 1, 1)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_D_INVESTIGATION, "Intelligence Report", villageDescs("Konoha Intelligence received a tip about rogue ninja organizing deep in Fire Country. The Will of Fire demands we protect this land. Investigate and destroy the cell.", "The Kazekage's office received a report of a rogue ninja cell massing near the desert border. They will not survive the sand. Hunt them down.", "ANBU intercepted communications about rogue ninja staging on the outer islands. Blood Mist standing order: find them, destroy them, leave no trace.", "Tsuchikage's intelligence division has a lead on enemy operatives in the mountain passes. The mountains are ours. Root them out.", "Kumogakure sensors detected foreign chakra signatures in the highland frontier. Our strength will not be questioned. Eliminate the source.", "Amegakure's rain detection system flagged intruders moving through the canal district. Security breach confirmed. Track and destroy.", "Reports of a rogue ninja cell. Investigate and eliminate."), (String)null, new StepTemplate[]{StepTemplate.combat("Ambushed on the road. They knew you were coming -- fight through them.", new String[]{"d_bandit_1", "d_bandit_2"}, 2, 3), StepTemplate.combatOffset("Following the blood trail to the informant's location. It is compromised -- hostiles everywhere.", new String[]{"d_rogue_genin_1", "d_rogue_genin_2"}, 2, 3, 200, 400), StepTemplate.combatOffset("Smoke rising from the next ridge. The enemy lookout post in {terrain}. Assault it.", new String[]{"d_rogue_genin_2", "d_rogue_genin_3", "d_assassin_1"}, 2, 3, 300, 500), StepTemplate.combatOffset("The hideout entrance. They are barricaded inside. Storm it and wipe them out.", new String[]{"d_rogue_genin_3", "d_mercenary_1", "d_mercenary_2"}, 3, 4, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_D_BORDER, "Border Incident", villageDescs("Border guards report a breach at the southern Fire Country checkpoint. Multiple hostile groups. For the Will of Fire -- respond immediately.", "The sand wall perimeter was breached near the western dunes. Multiple waves incoming. The desert will bury them -- with your help.", "An unauthorized boat landed on the northern shore. Armed groups spreading out through the fog. Blood Mist response authorized.", "The mountain pass guard tower was attacked. Multiple enemy squads detected in the gorge. Tsuchikage's orders: hold the mountains.", "Lightning barrier sensors triggered at the eastern ridge. Large-scale hostile incursion confirmed. Kumogakure's pride demands a swift response.", "The outer canal locks were forced open. Multiple armed groups entering from the south. Full security alert -- seal the breach.", "Border checkpoint breached. Multiple hostile groups detected. Respond immediately."), (String)null, new StepTemplate[]{StepTemplate.combat("First contact at the {terrain} border. Intercept and hold.", new String[]{"d_bandit_1", "d_bandit_2", "d_bandit_3"}, 2, 3), StepTemplate.combatOffset("A second wave pushing through. They are more organized -- hold your ground.", new String[]{"d_bandit_2", "d_bandit_3", "d_rogue_genin_1"}, 2, 3, 0, 0), StepTemplate.combatOffset("The survivors are scattering into {terrain}. Pursue them -- do not let them regroup.", new String[]{"d_bandit_3", "d_assassin_1", "d_rogue_genin_2"}, 2, 3, 300, 500), StepTemplate.combatOffset("The enemy leader is cornered. Finish this.", new String[]{"d_mercenary_2", "d_assassin_1"}, 1, 2, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_D_SUPPLY, "Supply Line Defense", villageDescs("The supply route between Konoha and the southern outpost is under siege. Fire Country's people depend on these roads. Clear every hostile along the route.", "Caravans between Sunagakure and the oasis settlements are being hit at multiple points. Without supplies, the outer camps die. Secure the route.", "The shipping lane between Kirigakure and the outer islands is compromised at multiple ports. Blood Mist protocol: clear them all, no exceptions.", "The ore transport route through the mountain tunnels is blocked at several points. Iwagakure's production depends on this. Fight through.", "Supply convoys to the mountain peak outposts are being ambushed repeatedly. Kumogakure's frontier garrisons need those supplies. Eliminate all threats.", "Medical supplies are not reaching the outer settlements. Multiple bandit groups blocking the canal routes. Full clearance authorized. Wipe them out.", "Supply routes are under siege at multiple points. Clear all hostiles."), (String)null, new StepTemplate[]{StepTemplate.combat("A crude blockade at the first checkpoint in {terrain}. Bandits with weapons drawn. Clear them.", new String[]{"d_bandit_1", "d_bandit_2", "d_bandit_2"}, 2, 3), StepTemplate.combatOffset("Reinforcements arriving from the treeline. They were waiting for this -- defend your position.", new String[]{"d_bandit_2", "d_bandit_3", "d_rogue_genin_1"}, 2, 3, 0, 0), StepTemplate.combatOffset("Pushing forward through {terrain} to the second checkpoint. More hostiles dug in ahead.", new String[]{"d_bandit_3", "d_bandit_3", "d_rogue_genin_2"}, 3, 3, 300, 500), StepTemplate.combatOffset("The ambush leader is cornered with their last fighters. No retreat for either of you.", new String[]{"d_mercenary_1", "d_mercenary_2", "d_bandit_3"}, 2, 3, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_D_HIDEOUT, "Hideout Raid", villageDescs("Konoha's tracking unit located a bandit headquarters deep in the forest. The Will of Fire means leaving no threat to our people. Assault and destroy it.", "A hidden base was discovered beneath the sand dunes near the western canyon. They thought the desert would hide them. Breach and clear.", "Smugglers have a fortified warehouse hidden in the fog banks along the coast. Blood Mist protocol: raid it, burn it, leave nothing.", "An underground base was found in the abandoned mines above the gorge. Tsuchikage's direct order: infiltrate and eliminate all hostiles.", "A fortified camp was spotted on an isolated clifftop overlooking the highland road. Kumogakure does not tolerate vermin in our mountains. Storm it.", "An old factory in the outer wetlands is being used as an armed base. Sensor grid confirmed multiple hostiles. Assault and clear.", "A hidden enemy base has been located. Assault and destroy."), (String)null, new StepTemplate[]{StepTemplate.combat("Perimeter guards spotted around the hideout in {terrain}. Take them out quietly.", new String[]{"d_bandit_1", "d_bandit_2", "d_bandit_3"}, 2, 3), StepTemplate.combatOffset("The entrance is ahead. Blades drawn inside -- breach now.", new String[]{"d_rogue_genin_1", "d_rogue_genin_2", "d_assassin_1", "d_assassin_2"}, 2, 3, 50, 100), StepTemplate.combatOffset("The inner chamber. Their best fighters are making a last stand. Wipe them out.", new String[]{"d_bandit_3", "d_rogue_genin_3", "d_mercenary_1", "d_mercenary_2"}, 4, 5, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_D_WANDERER, "Wandering Threat", (Map)null, "Reports of armed bandits harassing travelers on a remote road. Any available shinobi -- respond immediately.", new StepTemplate[]{StepTemplate.travel("Follow the road to the reported disturbance."), StepTemplate.combat("Armed figures ahead, blocking the road. Drive them off.", new String[]{"d_bandit_1", "d_bandit_2", "d_bandit_3", "d_road_bandit", "d_sand_bandit"}, 2, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_D_DUEL, "Open Bounty", (Map)null, "An open bounty has been posted for a dangerous mercenary operating in the area. First shinobi to find them claims the reward.", new StepTemplate[]{StepTemplate.travel("Follow the trail to the bounty target's last known position."), StepTemplate.combat("Target spotted. A professional -- they will not surrender quietly.", new String[]{"d_mercenary_1", "d_mercenary_2"}, 1, 1)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_D_AMBUSH, "Roadside Ambush", (Map)null, "Travelers are being ambushed along a remote road. Overturned carts and blood on the path. Clear the area before more victims fall.", new StepTemplate[]{StepTemplate.travel("Broken carts ahead. Approach the ambush site carefully."), StepTemplate.combat("Movement in the treeline -- the ambushers are still here. Flush them out.", new String[]{"d_bandit_1", "d_assassin_1", "d_assassin_2", "d_road_bandit"}, 2, 4)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_D_ROGUES, "Rogue Patrol", (Map)null, "Multiple rogue ninja sightings in the area. At least two groups operating independently. Sweep and eliminate all hostiles.", new StepTemplate[]{StepTemplate.travel("Head to the area where the first rogue ninja were spotted."), StepTemplate.combat("Contact. Two rogues ahead -- weapons drawn. Take them down.", new String[]{"d_rogue_genin_1", "d_rogue_genin_2"}, 1, 2), StepTemplate.combatOffset("Tracks leading deeper. The second group is close.", new String[]{"d_rogue_genin_2", "d_rogue_genin_3"}, 1, 2, 200, 400)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_D_ESCORT, "Clear the Path", (Map)null, "A merchant needs the road ahead cleared of bandits. Two groups blocking the route at separate chokepoints.", new StepTemplate[]{StepTemplate.travel("Head to the first chokepoint along the road."), StepTemplate.combat("Bandits blocking the path. Weapons out. Clear them.", new String[]{"d_bandit_1", "d_bandit_2"}, 2, 3), StepTemplate.combatOffset("The second group is dug in further down the road. Tougher this time.", new String[]{"d_bandit_2", "d_bandit_3", "d_mercenary_1"}, 2, 3, 200, 400)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_C_ESCORT, "Trade Route Escort", villageDescs("A merchant caravan heading through the forests east of Konoha has requested escort. Bandits with combat training are targeting the road near the border. Protect Fire Country's trade.", "A supply caravan crossing the desert wastes has gone silent. Bandits have been hitting the dune routes -- organized, armed, dangerous. The desert will not claim our people today.", "Cargo shipments along the fog-shrouded coastal route have been raided. Armed men with jutsu training spotted near the harbor. Blood Mist response: eliminate the blockade.", "Ore transports through the mountain passes are being hijacked. Bandits have fortified a narrow pass with a rogue ninja. Tsuchikage's orders: break through.", "Highland merchants report a blockade on the ridge road by trained fighters. Kumogakure's trade will not be disrupted. Remove the obstruction.", "Medical supply runners intercepted in the canal district. Armed thugs with a rogue ninja have set up checkpoints. Sensor-confirmed -- clear them.", "Bandits with combat training are blocking a major trade route. Clear the roadblock."), (String)null, new StepTemplate[]{StepTemplate.travel("Follow the trade road through {terrain} to the reported blockade."), StepTemplate.combat("The roadblock is ahead. Armed men -- at least one knows jutsu. Take them down.", new String[]{"c_enforcer_1", "c_enforcer_1", "c_rogue_genin_wind"}, 3, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_C_AMBUSH, "Ambush Response", villageDescs("ANBU intercepted communications about an ambush planned along the forest road south of Konoha. They are targeting our patrols. Get there first and turn it around.", "Desert scouts report suspicious activity near an oasis waystation. Concealed hostiles with jutsu training. Spring their ambush on your own terms.", "Fishermen saw armed figures hiding among the reef caves -- at least one with jutsu. An ambush being prepared for the harbor patrol. Blood Mist protocol: hit them first.", "An informant warned of rogue ninja hiding in an abandoned mine tunnel, planning to ambush an ore patrol. Tsuchikage's directive: flush them out before our miners pay the price.", "Thunder plateau scouts detected concealed hostiles near the cliffside trail. Jutsu users among them. Kumogakure turns the trap -- hit them before they know you are there.", "Sensor readings detected concealed chakra signatures near the drainage tunnels. Two signatures are elevated -- jutsu capability confirmed. Preemptive strike authorized.", "Intelligence reports an ambush waiting at a key location. Counter it before they spring the trap."), (String)null, new StepTemplate[]{StepTemplate.travel("Move quietly through {terrain} toward the ambush site."), StepTemplate.combat("There -- concealed among the terrain. Spring the counter-ambush now!", new String[]{"c_enforcer_1", "c_rogue_genin_fire", "c_rogue_genin_lightning"}, 3, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_C_ROGUE_DUO, "Rogue Ninja Pair", villageDescs("Two rogue ninja have been harassing travelers between Konoha and the border. They coordinate their attacks -- one slows with water jutsu, the other flanks. The Will of Fire will not let them prey on our people.", "A duo of desert rogues raiding caravans near the canyon passes. One traps, the other strikes. They know this terrain. The desert breeds killers -- prove you are better.", "Two missing-nin spotted in the fog banks along the eastern shore. Hit-and-run tactics, water jutsu coordination. Blood Mist protocol: hunt them through the fog.", "A pair of rogue genin terrorizing miners in the mountain passes. One uses water jutsu while the other tracks. Tsuchikage's bounty: eliminate both.", "Two rogue operatives intercepting message runners on the mountain paths. Coordinated -- one delays, the other kills. Kumogakure's communications will not be disrupted.", "A pair of rogue ninja defectors sabotaging infrastructure in the outer canal district. Sensor data shows they work as a team. Terminate both.", "A dangerous pair of rogue ninja has been spotted. They fight as a coordinated team -- expect water jutsu and flanking."), (String)null, new StepTemplate[]{StepTemplate.travel("Follow the trail through {terrain}. The pair was last spotted nearby."), StepTemplate.combat("Two figures ahead. They see you -- and they are moving to flank. Engage before they set up.", new String[]{"c_missing_nin_water", "c_tracker_nin"}, 2, 2)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_C_CAMP, "Bandit Stronghold", villageDescs("A fortified bandit camp has been found deep in the forests north of Konoha. Their leader knows Fire Style -- a former academy student. For Fire Country's safety, burn it down.", "Bandits have dug in at an abandoned outpost in the dunes. A former genin is directing them -- organized, dangerous. The desert will reclaim what is ours.", "A criminal gang has taken over a sea cave complex along the fog-shrouded coast. Their boss is an ex-ninja with water training. Blood Mist orders: leave no one standing.", "An armed group has fortified an abandoned mining outpost in the mountains. Their leader has real combat training. Tsuchikage's directive: reclaim the outpost.", "Bandits have established a cliffside camp overlooking a major highland trade route. A rogue ninja commands them. Kumogakure will not tolerate this. Storm it.", "A criminal gang has taken control of a decommissioned pump station in the outer district. Their leader is an armed rogue with jutsu training. Full assault authorized.", "A bandit camp with an ex-ninja leader has been located. Expect organized resistance with jutsu capability. Assault and eliminate."), (String)null, new StepTemplate[]{StepTemplate.travel("Campfire smoke visible through the {terrain}. The stronghold is ahead."), StepTemplate.combat("Fortified positions, armed sentries. Their leader knows jutsu. Storm the camp.", new String[]{"c_enforcer_1", "c_enforcer_2", "c_thug_heavy", "c_rogue_genin_fire"}, 4, 4)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_C_BOUNTY, "Chunin Bounty Target", villageDescs("A rogue chunin has been identified hiding in the Fire Country forests. Former Leaf -- knows Fire Style and Body Replacement. They dishonor everything Konoha stands for.", "A wanted missing-nin has been tracked to a cave in the desert badlands. Former chunin-rank, survived the desert this long. The sand will claim them today.", "A bounty target has surfaced on one of the outer islands. Former chunin-class, hiding in the fog. Mist does not forget its traitors.", "A rogue chunin has been spotted in the mountain ravines. Expect advanced combat techniques. The Tsuchikage's bounty board -- high value.", "A wanted missing-nin has been located in the highland caves. Chunin-level threat with substitution capability. Kumogakure's strength will bring them down.", "A high-value bounty target cornered in the industrial sector. Former chunin, dangerous and desperate. Sensor lock confirmed. Eliminate.", "A priority bounty has been issued for a rogue chunin. Armed, knows substitution jutsu. Approach with extreme caution."), (String)null, new StepTemplate[]{StepTemplate.travel("The trail leads deeper into {terrain}. The target is hiding nearby."), StepTemplate.combat("There. A trained chunin -- they have seen you. Expect substitution and elemental jutsu. Do not hold back.", new String[]{"c_chunin_captain_fire"}, 1, 1)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_C_TRADE_ROUTE, "Trade Route Pacification", villageDescs("The main trade route between Konoha and the southern border has been seized by a bandit network led by a rogue chunin. Four checkpoints occupied. For the Will of Fire -- liberate every one.", "Desert trade caravans report multiple ambush points along the dune corridor. An organized ring with rogue ninja backing. Without this route, the outer oases starve.", "The island shipping lane has been blockaded at multiple points by armed pirates with ninja support. Blood Mist protocol: break the blockade. Leave no pirate breathing.", "The mountain ore transport route has been cut off by a bandit army with rogue ninja at every chokepoint. Tsuchikage's priority order: smash through every position.", "Highland supply convoys attacked at multiple points along the ridge road. A coordinated bandit operation with missing-nin leadership. Kumogakure will reclaim every meter.", "The canal supply network compromised at four junctions. Armed gangs with rogue ninja support holding critical infrastructure. Full clearance authorized -- retake all points.", "A trade route has been seized at multiple points. Clear each checkpoint and eliminate the leadership."), (String)null, new StepTemplate[]{StepTemplate.combat("The first roadblock at the {terrain} checkpoint. Armed sentries and a jutsu user. Hit them hard.", new String[]{"c_enforcer_1", "c_rogue_genin_water", "c_enforcer_2"}, 3, 3), StepTemplate.combatOffset("Pushing forward. A second group with multiple jutsu users dug in at the crossing.", new String[]{"c_enforcer_2", "c_rogue_genin_wind", "c_rogue_genin_fire"}, 3, 3, 300, 500), StepTemplate.combatOffset("The route narrows ahead. A heavy guard with a tracker ninja and a wind user. Tight quarters.", new String[]{"c_thug_heavy", "c_missing_nin_wind", "c_tracker_nin"}, 3, 3, 300, 500), StepTemplate.combatOffset("The bandit leader's camp at the end of the route. Three trained fighters making their stand.", new String[]{"c_missing_nin_fire", "c_missing_nin_water", "c_chunin_captain_fire"}, 3, 3, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_C_INVESTIGATION, "Missing-Nin Cell", villageDescs("ANBU has identified a cell of rogue ninja conducting reconnaissance near Konoha. They are mapping our patrol routes. For the safety of the village, dismantle the cell.", "A rogue ninja cell has been spotted in the desert outskirts gathering intelligence on Suna's defenses. They know our canyon passes too well. Find them before they report back.", "Foreign operatives detected on the outer islands. A cell of missing-nin conducting surveillance on our harbor defenses. Blood Mist protocol: total elimination. No intel leaves the islands.", "Rogue ninja have established a covert observation post in the mountain passes, monitoring our ore shipments. Tsuchikage's order: root them out before they sell our routes.", "A missing-nin cell operating in the highland frontier intercepting courier messages. Kumogakure's communications are sacred. Destroy every last one of them.", "A rogue ninja cell has infiltrated the outer districts, conducting sabotage on sensor infrastructure. Security breach -- critical priority. Eliminate the cell.", "A missing-nin cell has been identified operating in the area. Meet your contact and dismantle the operation."), (String)null, new StepTemplate[]{StepTemplate.dialogNearVillage("Meet your intelligence contact in {terrain}.", "c_village_contact", new String[]{"Three weeks I've been watching them. Five operatives -- maybe six. Their leader is ex-chunin, knows substitution. They rotate lookouts every four hours. I've marked the gaps in their patrol."}, new String[]{"I'll hit the lookouts first, then push to the hideout."}), StepTemplate.combatOffset("The first lookout pair. Take them down before they signal the others.", new String[]{"c_rogue_genin_fire", "c_rogue_genin_wind"}, 2, 2, 200, 400), StepTemplate.combatOffset("Three more guarding the hideout entrance. They heard something -- they are on alert.", new String[]{"c_rogue_genin_lightning", "c_rogue_genin_water", "c_missing_nin_water"}, 3, 3, 300, 500), StepTemplate.combatOffset("The hideout. The cell leader is inside with their best fighters. Breach and eliminate.", new String[]{"c_chunin_captain_fire", "c_missing_nin_lightning", "c_tracker_nin"}, 3, 3, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_C_LIBERATION, "Settlement Liberation", villageDescs("A farming village south of Konoha has been seized by a bandit army with rogue ninja leadership. Civilians are trapped inside. The Will of Fire demands their liberation.", "An oasis trading post taken over by desert raiders backed by rogue ninja. Merchants are held hostage. The desert does not abandon its own -- free them.", "A fishing village on the eastern islands occupied by a pirate crew with missing-nin leadership. Blood Mist protocol: liberate the settlement. Kill every occupier.", "Bandits have taken control of a mining camp in the outer mountains, enslaving the miners. Tsuchikage's direct order: reclaim the camp by force.", "A mountain relay station seized by an organized criminal force. Communications operators held hostage. Kumogakure's infrastructure will be reclaimed. No negotiation.", "A water purification facility in the outer district seized by armed insurgents with rogue ninja. Workers held inside. Critical infrastructure -- full assault authorized.", "A settlement has been occupied by an armed force with rogue ninja. Civilians at risk. Assault and liberate."), (String)null, new StepTemplate[]{StepTemplate.combat("Perimeter guards around the occupied settlement in {terrain}. Hit them fast before they raise the alarm.", new String[]{"c_enforcer_1", "c_enforcer_1", "c_enforcer_2", "c_rogue_genin_fire"}, 4, 4), StepTemplate.combatOffset("Through the entrance. Heavier resistance inside -- a heavy and multiple jutsu users.", new String[]{"c_enforcer_2", "c_thug_heavy", "c_rogue_genin_water", "c_rogue_genin_lightning"}, 4, 4, 50, 100), StepTemplate.combatOffset("Pushing toward the center. The occupation's elite guard stands between you and the hostages.", new String[]{"c_missing_nin_fire", "c_missing_nin_wind", "c_rogue_genin_lightning"}, 3, 3, 50, 100), StepTemplate.combatOffset("The occupation leaders. Two rogue chunin making their last stand -- both know substitution. End this.", new String[]{"c_chunin_captain_water", "c_chunin_captain_lightning"}, 2, 2, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_C_BORDER, "Border Incursion Response", villageDescs("Multiple hostile groups have crossed the southern border into Fire Country. Jutsu users confirmed. A rogue chunin commands the operation. For the Will of Fire -- intercept every group.", "Foreign hostiles breached the Wind Country desert border at multiple points, moving toward interior supply lines. Organized incursion with ninja support. The desert will bury them.", "Hostile forces made landfall on the northern shores. Multiple boats -- a coordinated infiltration with missing-nin. Blood Mist protocol: not one of them leaves these islands alive.", "Armed groups crossed the mountain border through multiple passes. A coordinated probe with rogue ninja leading each squad. Tsuchikage's standing order: the mountains belong to Stone.", "Multiple hostile contacts at the lightning barrier perimeter. They have breached and are pushing inland with jutsu users. Kumogakure's pride demands total annihilation.", "Armed forces infiltrated through the canal locks at multiple entry points. Sensor-confirmed rogue ninja among them. Full security response -- seal the breach and eliminate.", "Multiple hostile groups have crossed the border with ninja support. Intercept all groups and hunt down the leader."), (String)null, new StepTemplate[]{StepTemplate.combat("First contact at the {terrain} border. A vanguard group with a wind user. Engage.", new String[]{"c_enforcer_1", "c_enforcer_2", "c_rogue_genin_wind"}, 3, 3), StepTemplate.combatOffset("A second group pushing deeper -- all trained genin with elemental jutsu.", new String[]{"c_rogue_genin_fire", "c_rogue_genin_water", "c_rogue_genin_lightning"}, 3, 3, 300, 500), StepTemplate.combatOffset("Smoke on the horizon. A heavy assault team -- tracker ninja and a missing-nin pushing for the interior.", new String[]{"c_thug_heavy", "c_missing_nin_lightning", "c_tracker_nin"}, 3, 3, 200, 400), StepTemplate.combatOffset("The incursion leader is cornered. A rogue chunin with their best fighter. No escape.", new String[]{"c_chunin_captain_wind", "c_missing_nin_fire"}, 2, 2, 0, 0), StepTemplate.dialogNearVillage("Report back to your commanding officer.", "c_village_contact", new String[]{"The border is secure. Four groups neutralized, command confirmed. Outstanding work, shinobi. Your village remembers this."}, new String[]{"Mission complete."})}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_C_TRAVELER, "Distress Signal", (Map)null, "A distress signal from travelers on a remote road. Armed bandits with at least one jutsu user among them. Any available shinobi -- respond immediately.", new StepTemplate[]{StepTemplate.travel("Smoke and shouting ahead. Move fast toward the distress signal."), StepTemplate.combat("Travelers pinned down by armed men. A fire jutsu user among the attackers. Engage now.", new String[]{"c_enforcer_1", "c_enforcer_2", "c_rogue_genin_fire"}, 3, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_C_BOUNTY, "Priority Bounty", (Map)null, "A priority bounty posted for a rogue chunin spotted in the area. Armed, knows substitution jutsu. High reward for any shinobi who can take them down.", new StepTemplate[]{StepTemplate.travel("Fresh tracks. The bounty target passed through here recently."), StepTemplate.combat("There -- the target. A trained chunin turning to face you. They know substitution. Do not let them escape.", new String[]{"c_chunin_captain_lightning"}, 1, 1)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_C_AMBUSH_DUO, "Paired Rogues", (Map)null, "A pair of missing-nin terrorizing the area. They work together -- one slows targets with water jutsu, the other follows up with fire. Dangerous coordination.", new StepTemplate[]{StepTemplate.travel("Scorch marks and water damage on the road. The rogue pair is nearby."), StepTemplate.combat("Two missing-nin stepping out of cover. Fire and water coordination -- break their rhythm or be caught between them.", new String[]{"c_missing_nin_fire", "c_missing_nin_water"}, 2, 2)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_C_SWEEP, "Area Sweep", (Map)null, "Multiple rogue ninja groups detected in the region. At least two separate cells with jutsu users. Sweep and neutralize all hostile contacts.", new StepTemplate[]{StepTemplate.travel("Moving to the first reported hostile position."), StepTemplate.combat("First cell found. Two rogue genin with elemental jutsu. Move in.", new String[]{"c_rogue_genin_water", "c_rogue_genin_wind"}, 2, 2), StepTemplate.combatOffset("The second cell is larger. A missing-nin with wind jutsu is leading them.", new String[]{"c_enforcer_2", "c_missing_nin_wind", "c_missing_nin_lightning", "c_rogue_genin_fire"}, 3, 3, 200, 400)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_C_ESCORT_CLEAR, "High-Value Route Clearing", (Map)null, "A high-value convoy needs a route cleared before it can proceed. Two bandit groups with rogue ninja blocking the road at separate chokepoints.", new StepTemplate[]{StepTemplate.travel("The first chokepoint is ahead. Move into position."), StepTemplate.combat("Heavy bandit presence at the first chokepoint. A heavy and a jutsu user among them.", new String[]{"c_enforcer_1", "c_thug_heavy", "c_rogue_genin_water"}, 3, 3), StepTemplate.combatOffset("The second group ahead. All trained rogues fighting as a coordinated squad.", new String[]{"c_rogue_genin_fire", "c_rogue_genin_wind", "c_tracker_nin"}, 3, 3, 200, 400)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_D_TRAINING_INTRUDER, "Training Grounds Intruder", villageDescs("Unknown individuals spotted near the genin training fields outside Konoha. The next generation trains there -- the Will of Fire demands we protect them. Investigate immediately.", "Trespassers detected in the puppet corps practice zone beyond the canyon walls. Our techniques are secrets of the sand. Remove them before they see anything.", "Unauthorized persons reported near the swordsmanship dojo on the eastern shore. Blood Mist protocol: our training grounds are sacred. No outsiders.", "Intruders spotted near the demolition training range in the upper mines. Tsuchikage's directive: our methods stay in Stone. Clear them out.", "Civilians wandering too close to the lightning jutsu practice grounds on the ridge. Kumogakure's techniques are our pride -- remove these trespassers.", "Unauthorized entry detected at the sensor training facility in the outer district. Security breach at a classified site. Eliminate the intruders immediately.", "Intruders spotted near the training grounds. Investigate and remove them."), (String)null, new StepTemplate[]{StepTemplate.travelNearVillage("Head to the training grounds near the village."), StepTemplate.combat("Two armed figures near the training field. They do not belong here. Drive them off.", new String[]{"d_bandit_1", "d_bandit_2"}, 2, 2)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_D_CARGO, "Lost Cargo Recovery", villageDescs("A supply cart was found abandoned on the forest road south of Konoha, its contents scattered. Bandits likely found it first. Recover what you can.", "A caravan dropped a shipment in the dune corridors during a sandstorm. Armed men were seen scavenging the site. Recover the cargo.", "Cargo washed ashore on the eastern coast after a storm. Armed scavengers are already there. Blood Mist orders: those supplies are ours.", "An ore cart broke loose on the mountain pass and tumbled into a ravine. Bandits have claimed the wreck site. Reclaim the cargo.", "Supply crates fell from a highland convoy in rough terrain. Scavengers moved in. Kumogakure's supplies will be recovered.", "A medical supply transport was abandoned near a collapsed bridge in the canal district. Armed looters on site. Recover the supplies.", "Lost cargo found with bandits at the recovery site. Clear them and secure the supplies."), (String)null, new StepTemplate[]{StepTemplate.travel("Follow the road through {terrain} to the cargo site."), StepTemplate.combat("Bandits at the cargo site, already loading what they can carry. Run them off.", new String[]{"d_bandit_2", "d_bandit_3", "d_road_bandit"}, 2, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_D_CHECKPOINT, "Checkpoint Assist", villageDescs("A border checkpoint on the southern forest road is short-staffed. Fill in on watch. Reports of bandits moving in the area.", "A desert checkpoint near the canyon pass needs reinforcement. Caravan scouts report armed figures approaching through the dunes.", "A harbor checkpoint on the fog-shrouded coast is undermanned. Smugglers have been testing the watch. Blood Mist protocol: hold the line.", "A gorge checkpoint in the mountain passes needs backup. Bandits have been probing the defenses. Reinforce the position -- hold the line.", "A highland checkpoint on the ridge road is undermanned. Armed groups spotted approaching. Kumogakure's gates will hold.", "A canal checkpoint in the outer district is understaffed. Sensor array detected movement nearby. Fill in and hold the position.", "A checkpoint needs reinforcement. Bandits approaching during your shift."), (String)null, new StepTemplate[]{StepTemplate.travel("Report to the checkpoint in {terrain}."), StepTemplate.combat("Movement ahead -- bandits approaching the checkpoint. Hold your position and drive them back.", new String[]{"d_bandit_1", "d_bandit_2", "d_bandit_3"}, 3, 4)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_D_FESTIVAL, "Festival Security", villageDescs("Konoha's spring festival is underway and security is stretched thin. You have been assigned to the outer perimeter. Expect trouble -- thieves and worse always come out during festivals.", "Sunagakure's harvest festival draws crowds from across Wind Country. Security detail on the outer dunes -- festival brings thieves like flies to an oasis.", "The Mist maritime festival is underway at the harbor. You are on security patrol. Blood Mist warning: we expect trouble. Deal with it permanently.", "Iwagakure's mining festival draws traders from across Earth Country. You have checkpoint duty outside the gorge. Tsuchikage's orders: no incidents.", "Kumogakure's thunder festival is in full swing on the plateau. Security detail assigned. Our festivals show our strength -- so should our response to trouble.", "Amegakure's industrial expo draws visitors from neighboring lands. Perimeter security assigned. Sensor grid on high alert -- any incident is a security breach.", "A village festival is underway. Security detail assigned to the perimeter. Expect trouble."), (String)null, new StepTemplate[]{StepTemplate.combat("Petty thieves causing trouble near the festival perimeter. Run them off.", new String[]{"d_bandit_1", "d_bandit_1", "d_bandit_2"}, 2, 3), StepTemplate.combatOffset("More organized this time. A gang moving through {terrain}, targeting festival-goers.", new String[]{"d_bandit_2", "d_bandit_3", "d_assassin_1"}, 2, 3, 100, 200), StepTemplate.combatOffset("They had a rogue genin backing them. Chasing the rest into the outskirts.", new String[]{"d_rogue_genin_1", "d_rogue_genin_2", "d_assassin_2"}, 2, 3, 200, 400), StepTemplate.combatOffset("The ringleader is cornered with their last fighters. End this before the festival is ruined.", new String[]{"d_mercenary_1", "d_mercenary_water"}, 1, 2, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_D_MISSING_PERSON, "Missing Person", villageDescs("A farmer went missing on the forest road three days ago. Last seen heading south through the treeline. Konoha does not abandon its people -- find them.", "A merchant disappeared on the desert trade route four days ago. The sand swallows the careless, but this was no accident. Find them.", "A fisherman vanished from the eastern shore two days ago. No wreckage, no body. Blood Mist does not lose track of its people. Investigate.", "A miner went missing in the mountain passes. Tsuchikage's order: find our worker and punish whoever took them.", "A supply runner disappeared on the highland road. Kumogakure does not leave its people behind. Find the runner.", "A canal maintenance worker vanished during a routine inspection in the outer district. Sensor logs show unknown contacts. Investigate.", "A civilian went missing on the road. Meet the informant and follow the trail."), (String)null, new StepTemplate[]{StepTemplate.dialogNearVillage("Meet the informant who reported the missing person.", "d_informant", new String[]{"Someone went missing on the road three days ago. Last seen heading {terrain}ward. I found drag marks leading off the main path -- and blood. Someone took them."}, new String[]{"I will find them. Show me where the trail starts."}), StepTemplate.combatOffset("Following the drag marks through {terrain}. Bandits blocking the trail -- they know what happened here.", new String[]{"d_bandit_1", "d_bandit_2"}, 2, 3, 200, 400), StepTemplate.combatOffset("Deeper into the wilderness. A makeshift camp -- more armed men guarding something.", new String[]{"d_bandit_3", "d_rogue_genin_1", "d_assassin_1"}, 2, 3, 200, 400), StepTemplate.combatOffset("The holding site. The captors and their leader. Break through and free the captive.", new String[]{"d_mercenary_lightning", "d_bandit_3", "d_rogue_genin_3"}, 2, 3, 100, 200)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_D_CAMP, "Abandoned Campsite", (Map)null, "Reports of an abandoned campsite with signs of struggle. Scattered belongings, overturned cookware. The occupants may still be nearby -- or their attackers might be.", new StepTemplate[]{StepTemplate.travel("Approach the abandoned campsite. Stay alert."), StepTemplate.combat("Not abandoned -- the attackers are still here, going through the loot. Drive them off.", new String[]{"d_bandit_2", "d_bandit_3", "d_road_bandit"}, 2, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_D_TRAP, "Traveler in Distress", (Map)null, "A traveler sent a distress signal from a remote location. Be cautious -- it could be a trap. Distress signals in the borderlands are not always what they seem.", new StepTemplate[]{StepTemplate.travel("Following the distress signal to a remote clearing. Something feels wrong."), StepTemplate.combat("It was a trap. Armed figures emerging from hiding. They wanted to lure a shinobi here.", new String[]{"d_assassin_1", "d_assassin_2", "d_bandit_3"}, 2, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_C_DEFECTOR, "Defector Intercept", villageDescs("A rogue ninja is fleeing through the Fire Country forests toward the border. Former genin with wind jutsu training. The Will of Fire cannot let a traitor escape with village secrets.", "A deserter from Suna's ranks is fleeing through the canyon passes toward Wind Country's border. They know our patrol routes. The desert does not forgive desertion.", "A defector from the Mist academy is running for the coast with stolen scrolls. Blood Mist protocol: intercept and eliminate. Nothing leaves these shores.", "A rogue ninja fleeing through the mountain passes toward the border with stolen mining maps. Tsuchikage's order: those maps do not leave Earth Country.", "A defector from Cloud's garrison is racing along the highland ridge toward the border. They carry knowledge of our barrier network. Kumogakure's secrets die with them.", "A former operative fleeing through the canal district toward the outer perimeter. Sensor lock active. Intercept before they reach the drainage outflow.", "A rogue ninja fleeing toward the border with stolen intelligence. Intercept and neutralize before they escape."), (String)null, new StepTemplate[]{StepTemplate.travel("The defector was last seen heading through {terrain}. Move fast."), StepTemplate.combat("There -- the defector with an escort. They are not going quietly. Cut them off.", new String[]{"c_rogue_genin_fire", "c_rogue_genin_wind", "c_enforcer_1"}, 2, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_C_SMUGGLER, "Smuggler Ring Bust", villageDescs("Contraband weapons are being moved through Fire Country's forest roads. An organized ring with rogue ninja muscle. Shut them down -- Fire Country's roads must be safe.", "Stolen jutsu scrolls are being smuggled through the desert trade routes. Armed guards with a rogue water user. The desert sand will be their grave.", "Contraband weapons being run through the fog-shrouded coastal harbors. An armed ring with ninja backing. Blood Mist protocol: seize the cargo, eliminate the runners.", "Stolen mining explosives being moved through the mountain tunnels. Armed smugglers with a rogue ninja escort. Tsuchikage's order: stop them in the tunnels.", "Illegal weapons shipment moving along the highland ridge road. Armed guards with trained fighters. Kumogakure will not allow this in our territory.", "Contraband materials moving through the canal infrastructure. Armed smugglers with a rogue ninja. Sensor-confirmed. Full interdiction authorized.", "A smuggling ring moving contraband through the area. Armed guards with rogue ninja. Shut them down."), (String)null, new StepTemplate[]{StepTemplate.travel("Intel points to a smuggler meeting point in {terrain}. Move to intercept."), StepTemplate.combat("The smugglers and their muscle. Armed guards and a rogue ninja protecting the cargo. Take them all down.", new String[]{"c_enforcer_1", "c_enforcer_2", "c_bandit_archer", "c_rogue_genin_water"}, 3, 4)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_C_OUTPOST, "Outpost Under Siege", villageDescs("A forward outpost in the forests south of Konoha is under attack by organized bandits with a jutsu user. The Will of Fire demands we hold every outpost. Reinforce immediately.", "An oasis waystation in the desert is under siege by raiders with a rogue ninja leading them. Those waystations keep our caravans alive. Respond now.", "A coastal watchtower on the eastern shore is being stormed by pirates with ninja support. Blood Mist standing order: our towers do not fall.", "A mining checkpoint in the mountain passes is being overrun by armed bandits with a jutsu-capable leader. Tsuchikage's order: reinforce and hold.", "A highland relay post is under attack by a raiding party with trained fighters. Kumogakure's infrastructure will be defended. Counterattack.", "A sensor relay station in the outer district is being assaulted by armed insurgents with rogue ninja support. Critical infrastructure -- emergency response.", "An outpost is under attack by organized bandits with jutsu users. Reinforce and repel the attackers."), (String)null, new StepTemplate[]{StepTemplate.travel("The outpost in {terrain} is under attack. Move fast -- they need reinforcement."), StepTemplate.combat("The outpost is surrounded. Armed fighters with at least two jutsu users. Break the siege.", new String[]{"c_enforcer_2", "c_thug_heavy", "c_rogue_genin_lightning", "c_assassin_fast"}, 3, 4)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_C_INFORMANT, "The Informant's Trail", villageDescs("An embedded operative has intelligence on a rogue ninja cell in Fire Country's forests. Meet them, then follow the trail to the source. This is how we protect Konoha.", "An intelligence asset embedded with desert raiders has critical information. Meet them at the oasis dead drop, then follow the trail into the dunes.", "A Mist operative embedded with coastal smugglers has mapped their entire network. Blood Mist protocol: extract the intel, then destroy the network completely.", "An informant inside a bandit group in the mountain passes has information on their base. Tsuchikage's intelligence division: meet the asset, then assault the target.", "An operative embedded with highland raiders has intelligence on their command structure. Kumogakure's spycraft at work. Extract the intel, then strike.", "A sensor analyst embedded in the outer district has tracked an infiltration cell. Meet the asset, follow the data trail, eliminate the cell.", "An embedded informant has intelligence on a rogue ninja operation. Meet them and follow the trail to eliminate the threat."), (String)null, new StepTemplate[]{StepTemplate.dialogNearVillage("Meet the embedded operative near the village.", "c_scout", new String[]{"I've been embedded with them for two weeks. Their scouts patrol the eastern ridge every six hours. The main force is camped beyond that -- twenty, maybe thirty armed. But only five are real threats. I've mapped the scout positions. Hit them first, then push through."}, new String[]{"Good work. I will start with the scouts and push to the camp."}), StepTemplate.travelOffset("Move to the scouting position the informant marked in {terrain}.", 200, 400), StepTemplate.combatOffset("The forward scouts. Two rogue genin -- take them down quietly.", new String[]{"c_rogue_genin_fire", "c_rogue_genin_wind"}, 2, 2, 100, 200), StepTemplate.combatOffset("Pushing deeper. A three-man squad with a missing-nin guarding the approach.", new String[]{"c_missing_nin_wind", "c_rogue_genin_lightning", "c_enforcer_2"}, 3, 3, 200, 400), StepTemplate.combatOffset("The main camp. The cell leader and their best fighters. Assault and eliminate.", new String[]{"c_chunin_captain_water", "c_missing_nin_fire", "c_tracker_nin"}, 3, 3, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_C_HUNTER, "Hunter Becomes Hunted", villageDescs("A high-value rogue ninja has been tracked to the forests east of Konoha. Be warned -- this target has eluded three previous teams. They know they are being hunted.", "A dangerous missing-nin has been cornered in the desert canyons. Three Sand teams failed to capture them. They are not running anymore -- they are setting traps.", "A notorious rogue ninja has been located on the outer islands. Mist hunter-nin lost contact pursuing them. Blood Mist warning: this target fights back.", "A high-value missing-nin tracked to the mountain ravines. Two previous teams went silent. Tsuchikage's warning: this one is dangerous and expects you.", "A rogue ninja has been hunted across the highland frontier for weeks. Every team sent after them was ambushed. Kumogakure demands this ends now.", "A dangerous operative has been located in the outer canal network. Sensor teams report the target is stationary -- possibly a trap. Proceed with extreme caution.", "A high-value rogue ninja target has been tracked to the area. Warning: previous teams were ambushed. The hunter may become the hunted."), (String)null, new StepTemplate[]{StepTemplate.combat("Found them -- two rogue genin appear. Too easy. This is the bait.", new String[]{"c_rogue_genin_fire", "c_rogue_genin_water"}, 2, 2), StepTemplate.combatOffset("It was a trap. Reinforcements closing in from behind -- a fast one and a missing-nin.", new String[]{"c_assassin_fast", "c_missing_nin_lightning", "c_enforcer_1"}, 3, 3, 100, 200), StepTemplate.combatOffset("More of them. They planned this well -- but you are still standing. Cut through them.", new String[]{"c_thug_heavy", "c_rogue_genin_wind", "c_missing_nin_wind"}, 3, 3, 200, 400), StepTemplate.combatOffset("The real target, at last. A rogue chunin with their best fighter. Now the hunter becomes the hunted.", new String[]{"c_chunin_captain_lightning", "c_chunin_captain_ranged"}, 2, 2, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_C_BOUNTY_PAIR, "Bounty Board Special", (Map)null, "Double bounty posted -- two missing-nin operating as a pair. One uses lightning jutsu, the other wind. They cover each other's weaknesses. High-value targets.", new StepTemplate[]{StepTemplate.travel("Two sets of tracks converging ahead. The bounty pair is close."), StepTemplate.combat("Both targets in sight. Lightning and wind -- they will try to overwhelm you with speed and range. Do not let them coordinate.", new String[]{"c_missing_nin_lightning", "c_missing_nin_wind"}, 2, 2)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_C_FIELD_DEFENSE, "Field Hospital Defense", (Map)null, "A field medical station is under threat from bandits with rogue ninja support. Medics and wounded are inside. Defend the station and secure the supply lines.", new StepTemplate[]{StepTemplate.travel("The medical station is ahead. Sounds of fighting -- move fast."), StepTemplate.combat("First wave hitting the station. Armed bandits with a ranged fighter. Protect the medics.", new String[]{"c_enforcer_1", "c_enforcer_2", "c_bandit_archer"}, 3, 3), StepTemplate.combatOffset("A second assault wave -- rogue ninja leading them this time. Heavier threat.", new String[]{"c_rogue_genin_fire", "c_assassin_fast", "c_missing_nin_water"}, 3, 3, 200, 400)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_B_PATROL, "Elite Border Patrol", villageDescs("ANBU reports a heavily armed mercenary squad operating along the eastern Fire Country border. Experienced fighters with elemental jutsu. The Will of Fire demands we keep our borders secure -- no matter who crosses them.", "A professional mercenary unit has been spotted moving through the deep desert near the Wind Country border. Elemental jutsu confirmed. The Kazekage's standing order: the sand devours all trespassers.", "A heavily armed squad detected near the outer reef islands. Multiple elemental jutsu users. Blood Mist protocol: our waters are sovereign. Not one of them leaves alive.", "Armed mercenaries with jutsu capability reported in the mountain frontier passes. Tsuchikage's border directive: these mountains belong to Stone. No exceptions, no mercy.", "A professional combat squad intercepted on the lightning ridge perimeter. They breached the barrier with jutsu. Kumogakure's borders are absolute -- remind them why.", "Sensor array detected a high-capability squad bypassing the outer canal checkpoints. Multiple elevated chakra signatures. Full military response authorized -- secure the perimeter.", "A heavily armed mercenary squad with elemental jutsu users has been detected at the border. Intercept and neutralize."), (String)null, new StepTemplate[]{StepTemplate.travel("Move through {terrain} to the border patrol sector. Intel says they are well-armed."), StepTemplate.combat("There -- a mercenary squad with jutsu users. Professionals. Hit them hard before they dig in.", new String[]{"b_merc_heavy", "b_merc_fire", "b_merc_lightning"}, 3, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_B_ROGUE_CELL, "Rogue Ninja Cell", villageDescs("Intelligence has confirmed a rogue chunin cell operating deep in Fire Country's forests. Coordinated elemental jutsu users -- fire and lightning. The Will of Fire will not tolerate organized threats to our people.", "A rogue ninja cell has established operations in the desert canyon network. Chunin-level operatives with elemental jutsu. The Kazekage's orders: dismantle the cell before they recruit more.", "Rogue chunin have been spotted coordinating attacks on the outer islands. Fire and lightning users working as a unit. Blood Mist standing order: total elimination. No prisoners.", "A rogue ninja cell has dug into the abandoned mines in the upper mountains. Chunin-rank, elemental jutsu confirmed. Tsuchikage's directive: collapse the cell, not the mine.", "Rogue chunin operating from a hidden position on the highland frontier. Coordinated elemental attacks on supply convoys. Kumogakure's strength will crush this cell.", "Sensor network has tracked a rogue ninja cell to the outer industrial sector. Chunin-level signatures, fire and lightning capability. Priority elimination authorized.", "A coordinated rogue chunin cell with elemental jutsu has been located. Eliminate both operatives."), (String)null, new StepTemplate[]{StepTemplate.travel("Follow the intelligence trail through {terrain} to the cell's operating area."), StepTemplate.combat("Two rogue chunin -- fire and lightning. They see you. Coordinated attack incoming.", new String[]{"b_rogue_chunin_fire", "b_rogue_chunin_lightning"}, 2, 2)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_B_BOUNTY, "High Bounty Target", villageDescs("A high-value bounty target has surfaced in Fire Country's deep forests. A specialist tracker with years of combat experience. The Will of Fire means bringing justice to those who prey on our people.", "A dangerous bounty target has been tracked to the desert badlands. A specialist tracker-nin who has evaded three Sand teams. The Kazekage has doubled the bounty. End this.", "A high-value target has been cornered on the fog-shrouded outer islands. A specialist tracker who killed two Mist hunter-nin. Blood Mist protocol: this one dies today.", "A priority bounty target located in the mountain ravines. A specialist tracker who has been mapping our trade routes. Tsuchikage's personal bounty. Bring proof.", "A high-value missing-nin detected on the highland frontier. A specialist tracker who has been intercepting our couriers. Kumogakure's pride demands this target falls.", "Sensor lock confirmed on a high-value bounty target in the outer canal network. A specialist tracker -- experienced, dangerous, and cornered. Terminate with extreme force.", "A high-value bounty has been posted for a specialist tracker-nin. Experienced and dangerous. Single target, high reward."), (String)null, new StepTemplate[]{StepTemplate.travel("The bounty target was last tracked through {terrain}. Fresh signs nearby."), StepTemplate.combat("There -- the specialist. They have seen you and are not running. This one fights back.", new String[]{"b_specialist_tracker"}, 1, 1)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_B_AMBUSH, "Ambush Response", villageDescs("A patrol team was ambushed on the forest road south of Konoha. Mixed hostiles -- mercenaries, rogues, and an assassin. Survivors report elemental jutsu and coordinated tactics. The Will of Fire demands we respond.", "An outpost guard team was hit in the desert passes. Coordinated ambush by mixed fighters -- water jutsu, wind jutsu, and a blade specialist. The Kazekage demands immediate retaliation.", "A harbor patrol was attacked by a mixed combat squad. Water user, wind user, and a silent killer. Blood Mist protocol: find the ambush team and leave no survivors.", "Mining escorts ambushed in the mountain tunnels. A mixed squad with water jutsu, wind jutsu, and an assassin. Tsuchikage's order: avenge our people and secure the route.", "A courier team ambushed on the highland ridge road. Professional fighters with mixed jutsu. Kumogakure does not forget. Find them and destroy them.", "A sensor team was attacked near the outer canal infrastructure. Three hostiles with mixed jutsu capability. Security breach -- immediate retaliatory strike authorized.", "A patrol team was ambushed by a mixed squad with elemental jutsu and an assassin. Respond and eliminate."), (String)null, new StepTemplate[]{StepTemplate.travel("Move to the ambush site through {terrain}. The attackers may still be nearby."), StepTemplate.combat("The ambush squad is still in the area. A water user, a wind user, and an assassin. Engage.", new String[]{"b_merc_water", "b_rogue_chunin_wind", "b_specialist_assassin"}, 3, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_B_OUTPOST, "Outpost Assault", villageDescs("An enemy outpost has been identified in Fire Country's eastern forests. Four hostiles -- heavy fighters and elemental jutsu users. The Will of Fire will not tolerate enemy strongholds on our soil. Assault and destroy.", "Desert scouts located an enemy forward base near the Wind Country border. Heavy fighters and rogue chunin with elemental jutsu. The Kazekage's directive: raze it to the sand.", "An enemy staging point on the outer islands has been confirmed. Four fighters with heavy weapons and elemental jutsu. Blood Mist protocol: assault and annihilate. Leave nothing standing.", "An enemy outpost in the abandoned upper mines. Four hostiles with heavy arms and jutsu capability. Tsuchikage's direct order: storm it, clear it, seal it.", "An enemy forward position detected on the highland plateau. Heavy fighters and jutsu users. Kumogakure's territory will be cleansed. Full assault authorized.", "Sensor grid confirmed an enemy outpost in the outer industrial zone. Four elevated signatures -- heavy weapons and jutsu. Full military assault authorized.", "An enemy outpost has been identified. Four hostiles with heavy weapons and elemental jutsu. Assault and destroy."), (String)null, new StepTemplate[]{StepTemplate.travel("The outpost is ahead in {terrain}. Four confirmed hostiles. Prepare for a full assault."), StepTemplate.combat("The outpost gates are in sight. Heavy fighters and jutsu users. Storm the position.", new String[]{"b_merc_heavy", "b_merc_fire", "b_rogue_chunin_water", "b_rogue_chunin_earth"}, 4, 4)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_B_ESCORT, "VIP Escort Defense", villageDescs("A high-value official is traveling through Fire Country under threat from professional killers. Three hostiles confirmed -- elemental jutsu users and a pyro specialist. The Will of Fire protects all who walk our roads.", "A diplomatic envoy crossing the desert is being stalked by a kill team. Fire user, pyro specialist, and a lightning fighter. The Kazekage's honor depends on this escort arriving alive.", "A Mist dignitary is being transported along the coast under threat from an assassination squad. Blood Mist protocol: the VIP lives, the attackers die. No other outcome is acceptable.", "An ore shipment overseer is being targeted in the mountain passes. Professional fighters with fire and lightning jutsu. Tsuchikage's order: protect the overseer at all costs.", "A Kumogakure ambassador is under threat on the highland road. A kill team with fire and lightning capability. The Cloud's honor rides on this escort. Failure is not an option.", "A high-value analyst is being moved through the canal district. An assassination team with elevated chakra signatures is closing in. Escort defense priority -- protect the asset.", "A VIP is being targeted by a professional kill team with elemental jutsu. Protect the escort and eliminate the attackers."), (String)null, new StepTemplate[]{StepTemplate.travel("Move to the escort rendezvous point in {terrain}. The kill team is closing in."), StepTemplate.combat("The kill team has engaged. Fire user, pyro specialist, lightning fighter. Protect the VIP.", new String[]{"b_rogue_chunin_fire", "b_specialist_pyro", "b_merc_lightning"}, 3, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_B_DEFECTOR, "Defector Elimination", villageDescs("A former jonin instructor has defected with classified training methodologies. They are traveling with a specialist guard. The Will of Fire cannot allow our secrets to leave. Both must be eliminated.", "A high-ranking defector is fleeing through the deep desert with an elite bodyguard. They carry Sand's puppet corps blueprints. The Kazekage's kill order: nothing survives the desert today.", "A former Mist intelligence officer has defected with classified harbor defense plans. Accompanied by a specialist guard. Blood Mist protocol: absolute termination. Both of them.", "A Stone village strategist has defected with mountain defense blueprints. Accompanied by a specialist fighter. Tsuchikage's priority order: kill both. Recover nothing -- destroy everything.", "A Cloud barrier specialist has defected with lightning network schematics. Traveling with an elite guard. Kumogakure's deepest secrets will not be sold. Both die.", "A former sensor analyst has defected with classified infrastructure maps. Moving through the canal district with a specialist escort. Maximum priority. Both targets terminated.", "A high-ranking defector is fleeing with classified intelligence, accompanied by a specialist guard. Both must be eliminated."), (String)null, new StepTemplate[]{StepTemplate.travel("The defector was tracked through {terrain}. Moving with a specialist guard. Both are targets."), StepTemplate.combat("The defector and their guard. A sentinel and a storm specialist. Both must fall.", new String[]{"b_specialist_sentinel", "b_specialist_storm"}, 2, 2)}));
      registerTemplate(new MissionTemplate(TemplateId.DAILY_B_SABOTAGE, "Sabotage Prevention", villageDescs("ANBU intercepted plans to sabotage a critical supply depot in Fire Country's forests. A mixed squad -- heavy fighter, rogue chunin, and an assassin. The Will of Fire demands we stop them before they reach the target.", "Intelligence warns of a sabotage team approaching Suna's water purification wells. Heavy fighter, lightning user, and a silent killer. Without those wells, the outer camps die. Stop them.", "A sabotage team is approaching the harbor defense mechanisms. Heavy weapons, a lightning user, and an assassin. Blood Mist protocol: the harbor defenses are sacred. Destroy the saboteurs.", "A sabotage squad is moving toward the main ore processing facility. Heavy fighter, lightning specialist, and an infiltrator. Tsuchikage's emergency order: protect the facility. Kill them all.", "A sabotage team is approaching the lightning barrier generators. Heavy fighter, rogue chunin, and an assassin specialist. Kumogakure's barrier is our shield. Defend it with your life.", "Sensor alert: a sabotage team approaching the main sensor relay hub. Heavy weapons, lightning jutsu, and an assassin. Critical infrastructure threat. Intercept immediately.", "A sabotage team is approaching critical infrastructure. Heavy fighter, lightning user, and an assassin. Intercept and eliminate."), (String)null, new StepTemplate[]{StepTemplate.travel("Move to intercept the sabotage team in {terrain}. They are already close to the target."), StepTemplate.combat("The sabotage squad -- a heavy, a lightning user, and an assassin. Stop them here.", new String[]{"b_merc_heavy", "b_rogue_chunin_lightning", "b_specialist_assassin"}, 3, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_B_CRIMINAL_ORG, "Criminal Organization Takedown", villageDescs("Konoha Intelligence has mapped an entire criminal organization operating in Fire Country. Multiple hideouts, escalating leadership. The Will of Fire demands we tear it out root and stem. This will be a long operation.", "The Kazekage's intelligence division has tracked a criminal syndicate running weapons through the desert corridor. Multiple hideout layers with rogue ninja at every level. Time to bury them under the sand.", "Mist ANBU has identified a criminal empire running contraband through the island chain. Multiple fortified positions with missing-nin muscle at every level. Blood Mist protocol: dismantle everything. Leave no trace.", "Tsuchikage's war council has identified a criminal network operating from abandoned mines. Multiple levels of defense with rogue ninja. Directive: collapse the entire operation.", "Kumogakure intelligence has uncovered a criminal organization embedded in the highland trade routes. Layered defenses with increasing skill levels. Our strength will crush every layer.", "A full criminal organization mapped by the sensor network. Multiple positions in the outer canal district, escalating security. Full dismantlement operation authorized.", "A criminal organization with multiple hideouts and escalating defenses. Infiltrate, escalate, and eliminate the leadership."), (String)null, new StepTemplate[]{StepTemplate.combat("The outer sentries in {terrain}. Low-tier muscle -- mercenaries and a rogue. Clear them quietly.", new String[]{"b_merc_heavy", "b_merc_fire", "b_rogue_chunin_wind"}, 3, 3), StepTemplate.combatOffset("The first hideout. More organized resistance -- a rogue chunin cell.", new String[]{"b_rogue_chunin_fire", "b_rogue_chunin_water", "b_rogue_chunin_lightning"}, 3, 3, 300, 500), StepTemplate.combatOffset("Deeper in. The elite guard -- specialist fighters protecting the inner sanctum.", new String[]{"b_specialist_tracker", "b_specialist_sentinel"}, 2, 2, 200, 400), StepTemplate.combatOffset("The final chamber. The organization's boss -- a jonin captain making their last stand.", new String[]{"b_jonin_captain_fire"}, 1, 1, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_B_BORDER_INVASION, "Border Incursion Response", villageDescs("A large-scale border incursion has been detected in eastern Fire Country. Multiple waves of increasingly skilled fighters pushing inland. The Will of Fire will not yield a single inch of our homeland.", "A coordinated assault on the Wind Country border. Multiple attack waves with escalating jutsu capability. The Kazekage's emergency directive: the sand wall holds. Repel every wave.", "An invasion force has made landfall on the northern islands. Multiple waves, each stronger than the last. Blood Mist protocol: drown them all in our waters. Not one boot stays on our shores.", "A coordinated border breach through multiple mountain passes. Each wave more dangerous than the last. Tsuchikage's wartime order: the mountains crush all invaders.", "A massive incursion at the lightning ridge perimeter. Multiple waves of fighters breaching the barrier. Kumogakure's absolute defense will not fall. Annihilate every wave.", "Large-scale infiltration through the canal network. Multiple waves detected by sensor grid, each with higher signatures. Full military response -- seal every entry point.", "A large-scale border incursion with multiple waves of increasingly skilled fighters. Repel all waves and hunt down the command element."), (String)null, new StepTemplate[]{StepTemplate.combat("First wave at the {terrain} border. Mercenaries and a rogue -- the vanguard. Intercept.", new String[]{"b_merc_heavy", "b_merc_fire", "b_rogue_chunin_wind", "b_merc_water"}, 4, 4), StepTemplate.combatOffset("Second wave pushing through. Heavier resistance -- rogue chunin with coordinated jutsu.", new String[]{"b_rogue_chunin_fire", "b_rogue_chunin_earth", "b_specialist_assassin"}, 3, 3, 300, 500), StepTemplate.combatOffset("The command element is pulling back. Specialist fighters covering the retreat. Press the attack.", new String[]{"b_specialist_tracker", "b_specialist_storm"}, 2, 2, 200, 400)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_B_JONIN_HUNT, "Rogue Jonin Hunt", villageDescs("A rogue jonin has been tracked deep into Fire Country's wilderness. They have scouts, guards, and they know they are being hunted. The Will of Fire demands this threat ends. Hunt them through every layer of defense.", "A dangerous rogue jonin has gone to ground in the deep desert canyons. Scout teams, guard details, layers of defense. The Kazekage's personal hunt order: no matter how deep they burrow.", "A rogue jonin who killed three Mist hunter-nin is holed up on the outer islands. Guards, traps, and scouts at every approach. Blood Mist protocol: no one escapes the fog. Hunt them down.", "A rogue jonin has established a fortified position in the deepest mountain tunnels. Layered defenses. Tsuchikage's directive: pursue through every tunnel. The mountains will be their tomb.", "A rogue jonin has been traced to the highest highland peaks. Scouts and guards at every approach. Kumogakure's pride demands this hunt succeeds. Our mountains, our rules.", "Sensor data has tracked a rogue jonin to a fortified position in the deepest canal infrastructure. Layered security. Full pursuit operation authorized. No escape routes.", "A rogue jonin with layered defenses has been located. Hunt them through scouts, guards, and elite fighters to the final confrontation."), (String)null, new StepTemplate[]{StepTemplate.combat("The jonin's outer scouts in {terrain}. Rogue chunin keeping watch. Take them down before they signal.", new String[]{"b_rogue_chunin_fire", "b_rogue_chunin_water"}, 2, 2), StepTemplate.combatOffset("Past the scouts. The guard detail -- chunin and specialists blocking the approach.", new String[]{"b_rogue_chunin_earth", "b_specialist_sentinel", "b_merc_heavy"}, 3, 3, 200, 400), StepTemplate.combatOffset("The inner perimeter. The jonin's personal guard -- their best fighters.", new String[]{"b_specialist_tracker", "b_jonin_captain_wind"}, 2, 2, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_B_INTEL_NETWORK, "Intelligence Network Raid", villageDescs("ANBU has mapped a hostile intelligence network operating in Fire Country. Multiple nodes gathering information on our defenses. The Will of Fire will not allow our secrets to bleed away. Destroy every node.", "The Kazekage's intelligence division has uncovered a spy network in the desert trade routes. Multiple information-gathering nodes. The sand will swallow their entire operation.", "Mist ANBU has identified a foreign intelligence network on the outer islands. Multiple observation posts feeding information to unknown masters. Blood Mist protocol: burn the entire network.", "A hostile spy network has been mapped in the mountain passes. Multiple nodes monitoring our ore shipments. Tsuchikage's directive: destroy every observation post. Our secrets stay in Stone.", "Foreign intelligence operatives have established a network across the highland frontier. Multiple nodes intercepting communications. Kumogakure's secrets are our power. Destroy them all.", "Sensor analysis has uncovered a hostile intelligence network in the canal infrastructure. Multiple data-gathering nodes. Full counter-intelligence sweep authorized.", "A hostile intelligence network with multiple nodes has been identified. Raid each position and destroy the entire network."), (String)null, new StepTemplate[]{StepTemplate.combat("The first intelligence node in {terrain}. Two operatives gathering data. Hit them fast.", new String[]{"b_rogue_chunin_water", "b_merc_lightning"}, 2, 2), StepTemplate.combatOffset("Moving to the second node. More operatives with a specialist relay runner.", new String[]{"b_rogue_chunin_fire", "b_rogue_chunin_wind", "b_specialist_assassin"}, 3, 3, 300, 500), StepTemplate.combatOffset("The central command node. The network's core handlers and their best guard.", new String[]{"b_specialist_sentinel", "b_jonin_captain_fire"}, 2, 2, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_B_SIEGE_DEFENSE, "Stronghold Defense", villageDescs("A forward stronghold in the Fire Country forests is under sustained assault. Multiple waves of increasingly dangerous enemies. The Will of Fire holds every position. Defend until the last attacker falls.", "A desert watchtower at the Wind Country border is under siege. Wave after wave of fighters hitting the walls. The Kazekage's order: the sand walls do not fall. Hold until they break.", "A coastal fortress on the eastern shore is being stormed by an assault force. Multiple waves of armed fighters. Blood Mist protocol: our walls are painted with enemy blood. Hold the fortress.", "A mountain garrison in the upper passes is under sustained attack. Wave after wave from the tunnels below. Tsuchikage's directive: the mountain holds. Fight them to the last.", "A highland relay station is under siege by a professional assault force. Multiple waves with escalating capability. Kumogakure's infrastructure will not fall. Hold the position.", "A critical sensor relay hub in the outer district is under assault. Multiple waves of armed attackers. The hub must not fall. Full defensive authorization.", "A stronghold is under sustained assault from multiple waves. Defend the position against increasingly dangerous attackers."), (String)null, new StepTemplate[]{StepTemplate.combat("First wave hitting the walls. Mercenaries and rogue fighters. Hold the line.", new String[]{"b_merc_heavy", "b_merc_fire", "b_rogue_chunin_wind"}, 3, 3), StepTemplate.combatOffset("Second wave. Heavier fighters with better coordination. Do not give ground.", new String[]{"b_rogue_chunin_water", "b_rogue_chunin_earth", "b_merc_lightning"}, 3, 3, 0, 0), StepTemplate.combatOffset("Third wave. Specialists leading the assault. Hold position.", new String[]{"b_specialist_tracker", "b_specialist_pyro"}, 2, 2, 0, 0), StepTemplate.combatOffset("Final wave. The assault commander with their elite guard. End this siege.", new String[]{"b_specialist_storm", "b_jonin_captain_wind"}, 2, 2, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.WEEKLY_B_KAGE_DIRECTIVE, "Kage's Special Directive", villageDescs("The Hokage has personally assigned this mission. A dangerous threat deep in Fire Country must be neutralized. Multiple layers of defense ending in a jonin-class target. Only the strongest carry the Will of Fire this far.", "The Kazekage's personal directive. A critical threat in the deep desert must be eliminated. Layered defenses, elite fighters, and a jonin-class target at the center. Only the desert's finest are sent on these missions.", "The Mizukage's personal hunt order. A high-priority target on the outermost islands with layers of professional defense. Blood Mist legacy: missions of this caliber define your career.", "Tsuchikage's direct command. A critical target deep in the mountain network with multiple defense layers. Only Stone's best receive directives from the Tsuchikage personally.", "The Raikage's personal assignment. A dangerous target in the highest peaks with elite guard details. Kumogakure's strongest carry missions like this. Make the Cloud proud.", "The village leader has issued a personal directive. A critical target deep in the outer infrastructure with heavy defenses. Highest classification. Success is the only option.", "A personal directive from the village leader. A dangerous target with multiple layers of elite defense. The hardest mission available."), (String)null, new StepTemplate[]{StepTemplate.combat("The first defense layer in {terrain}. Rogue chunin with elemental jutsu. Cut through them.", new String[]{"b_rogue_chunin_fire", "b_rogue_chunin_lightning"}, 2, 2), StepTemplate.combatOffset("Deeper. Three specialist fighters guarding the inner approach. No holding back.", new String[]{"b_specialist_tracker", "b_specialist_pyro", "b_specialist_sentinel"}, 3, 3, 200, 400), StepTemplate.combatOffset("The final chamber. A jonin captain -- the target. They have been waiting for this.", new String[]{"b_jonin_captain_fire"}, 1, 1, 0, 0)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_B_WANDERER, "Dangerous Wanderer", (Map)null, "Reports of two rogue chunin traveling together through the region. Elemental jutsu users -- fire and wind. They have been attacking convoys and vanishing. Any available jonin-class shinobi -- respond.", new StepTemplate[]{StepTemplate.travel("Scorched trees and wind-cut stone along the road. The rogue pair passed through recently."), StepTemplate.combat("Two rogue chunin ahead. Fire and wind users. They see you and are standing their ground.", new String[]{"b_rogue_chunin_fire", "b_rogue_chunin_wind"}, 2, 2)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_B_BOUNTY, "Specialist Bounty", (Map)null, "A priority bounty has been posted for a jonin-class target. A fire specialist with advanced combat capability. Single target, extremely dangerous. High reward for elimination.", new StepTemplate[]{StepTemplate.travel("The bounty target's trail is clear -- burnt foliage and scorched stone. Close now."), StepTemplate.combat("The jonin captain. A fire specialist standing in the open, waiting. They know you are here. This will not be easy.", new String[]{"b_jonin_captain_fire"}, 1, 1)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_B_AMBUSH_TRIO, "Coordinated Ambush", (Map)null, "Three professional fighters have been ambushing shinobi in the region. A tracker, an assassin, and a heavy -- they work as a coordinated kill team. Extremely dangerous.", new StepTemplate[]{StepTemplate.travel("Signs of a recent ambush ahead -- blood on the road, overturned supplies. They are close."), StepTemplate.combat("The ambush team reveals itself. A tracker, an assassin, and a heavy fighter. Coordinated attack -- break their formation.", new String[]{"b_specialist_tracker", "b_specialist_assassin", "b_merc_heavy"}, 3, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_B_SWEEP, "Area Sweep", (Map)null, "Multiple rogue chunin detected in the region. At least three with elemental jutsu -- earth, water, and a mercenary. Sweep the area and neutralize all hostiles.", new StepTemplate[]{StepTemplate.travel("Moving to the reported hostile concentration. Multiple chakra signatures ahead."), StepTemplate.combat("Three hostiles. Rogue chunin with earth and water jutsu, and an armed mercenary. Engage.", new String[]{"b_rogue_chunin_earth", "b_rogue_chunin_water", "b_merc_water"}, 3, 3)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_B_DUO, "Elite Duo", (Map)null, "Two specialist fighters operating as a pair -- a pyro specialist and a storm user. They complement each other's elements perfectly. Only experienced shinobi should engage.", new StepTemplate[]{StepTemplate.travel("Burn marks and lightning-scarred terrain ahead. The specialist duo is nearby."), StepTemplate.combat("The specialists -- pyro and storm. Fire and lightning working in tandem. Break their synergy or be overwhelmed.", new String[]{"b_specialist_pyro", "b_specialist_storm"}, 2, 2)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_B_CHECKPOINT, "Checkpoint Assault", (Map)null, "A heavily fortified checkpoint has been established by hostile forces. Four fighters -- a heavy, a fire user, a lightning user, and a sentinel. Full assault required.", new StepTemplate[]{StepTemplate.travel("The fortified checkpoint is visible ahead. Four hostile signatures. Prepare for a full engagement."), StepTemplate.combat("Fortified positions with four fighters. A heavy, fire user, lightning user, and a sentinel. Storm the checkpoint.", new String[]{"b_merc_heavy", "b_merc_fire", "b_rogue_chunin_lightning", "b_specialist_sentinel"}, 4, 4)}));
      registerTemplate(new MissionTemplate(TemplateId.RANDOM_B_HUNTER, "Hunter-Nin Encounter", (Map)null, "A jonin captain with a specialist tracker has been intercepting shinobi in the region. A wind specialist and a professional tracker working together. Extremely dangerous pair.", new StepTemplate[]{StepTemplate.travel("Fresh wind-cut marks on the terrain. A jonin captain's handiwork. They are close."), StepTemplate.combat("The jonin captain and their tracker. Wind specialist and a professional hunter. Both must fall.", new String[]{"b_jonin_captain_wind", "b_specialist_tracker"}, 2, 2)}));
   }

   private static void registerTemplate(MissionTemplate template) {
      TEMPLATES.put(template.id, template);
   }

   public static MissionTemplate get(TemplateId id) {
      return (MissionTemplate)TEMPLATES.get(id);
   }

   public static MissionTemplate randomDaily(Random random) {
      return randomDaily(QuestDefinition.QuestRank.D, random);
   }

   public static MissionTemplate randomDaily(QuestDefinition.QuestRank rank, Random random) {
      TemplateId[] dPool = new TemplateId[]{TemplateId.DAILY_D_PATROL, TemplateId.DAILY_D_GATEGUARD, TemplateId.DAILY_D_GENINHUNT, TemplateId.DAILY_D_CAMPRAID, TemplateId.DAILY_D_BOUNTY, TemplateId.DAILY_D_TRAINING_INTRUDER, TemplateId.DAILY_D_CARGO, TemplateId.DAILY_D_CHECKPOINT};
      TemplateId[] cPool = new TemplateId[]{TemplateId.DAILY_C_ESCORT, TemplateId.DAILY_C_AMBUSH, TemplateId.DAILY_C_ROGUE_DUO, TemplateId.DAILY_C_CAMP, TemplateId.DAILY_C_BOUNTY, TemplateId.DAILY_C_DEFECTOR, TemplateId.DAILY_C_SMUGGLER, TemplateId.DAILY_C_OUTPOST};
      TemplateId[] bPool = new TemplateId[]{TemplateId.DAILY_B_PATROL, TemplateId.DAILY_B_ROGUE_CELL, TemplateId.DAILY_B_BOUNTY, TemplateId.DAILY_B_AMBUSH, TemplateId.DAILY_B_OUTPOST, TemplateId.DAILY_B_ESCORT, TemplateId.DAILY_B_DEFECTOR, TemplateId.DAILY_B_SABOTAGE};
      TemplateId[] pool = buildPool(rank, dPool, cPool, bPool);
      return (MissionTemplate)TEMPLATES.get(pool[random.nextInt(pool.length)]);
   }

   public static MissionTemplate randomWeekly(Random random) {
      return randomWeekly(QuestDefinition.QuestRank.D, random);
   }

   public static MissionTemplate randomWeekly(QuestDefinition.QuestRank rank, Random random) {
      TemplateId[] dPool = new TemplateId[]{TemplateId.WEEKLY_D_INVESTIGATION, TemplateId.WEEKLY_D_BORDER, TemplateId.WEEKLY_D_SUPPLY, TemplateId.WEEKLY_D_HIDEOUT, TemplateId.WEEKLY_D_FESTIVAL, TemplateId.WEEKLY_D_MISSING_PERSON};
      TemplateId[] cPool = new TemplateId[]{TemplateId.WEEKLY_C_TRADE_ROUTE, TemplateId.WEEKLY_C_INVESTIGATION, TemplateId.WEEKLY_C_LIBERATION, TemplateId.WEEKLY_C_BORDER, TemplateId.WEEKLY_C_INFORMANT, TemplateId.WEEKLY_C_HUNTER};
      TemplateId[] bPool = new TemplateId[]{TemplateId.WEEKLY_B_CRIMINAL_ORG, TemplateId.WEEKLY_B_BORDER_INVASION, TemplateId.WEEKLY_B_JONIN_HUNT, TemplateId.WEEKLY_B_INTEL_NETWORK, TemplateId.WEEKLY_B_SIEGE_DEFENSE, TemplateId.WEEKLY_B_KAGE_DIRECTIVE};
      TemplateId[] pool = buildPool(rank, dPool, cPool, bPool);
      return (MissionTemplate)TEMPLATES.get(pool[random.nextInt(pool.length)]);
   }

   public static MissionTemplate randomRandom(Random random) {
      return randomRandom(QuestDefinition.QuestRank.D, random);
   }

   public static MissionTemplate randomRandom(QuestDefinition.QuestRank rank, Random random) {
      TemplateId[] dPool = new TemplateId[]{TemplateId.RANDOM_D_WANDERER, TemplateId.RANDOM_D_DUEL, TemplateId.RANDOM_D_AMBUSH, TemplateId.RANDOM_D_ROGUES, TemplateId.RANDOM_D_ESCORT, TemplateId.RANDOM_D_CAMP, TemplateId.RANDOM_D_TRAP};
      TemplateId[] cPool = new TemplateId[]{TemplateId.RANDOM_C_TRAVELER, TemplateId.RANDOM_C_BOUNTY, TemplateId.RANDOM_C_AMBUSH_DUO, TemplateId.RANDOM_C_SWEEP, TemplateId.RANDOM_C_ESCORT_CLEAR, TemplateId.RANDOM_C_BOUNTY_PAIR, TemplateId.RANDOM_C_FIELD_DEFENSE};
      TemplateId[] bPool = new TemplateId[]{TemplateId.RANDOM_B_WANDERER, TemplateId.RANDOM_B_BOUNTY, TemplateId.RANDOM_B_AMBUSH_TRIO, TemplateId.RANDOM_B_SWEEP, TemplateId.RANDOM_B_DUO, TemplateId.RANDOM_B_CHECKPOINT, TemplateId.RANDOM_B_HUNTER};
      TemplateId[] pool = buildPool(rank, dPool, cPool, bPool);
      return (MissionTemplate)TEMPLATES.get(pool[random.nextInt(pool.length)]);
   }

   private static TemplateId[] buildPool(QuestDefinition.QuestRank rank, TemplateId[] dPool, TemplateId[] cPool, TemplateId[] bPool) {
      if (rank.ordinal() >= QuestDefinition.QuestRank.B.ordinal()) {
         TemplateId[] pool = new TemplateId[dPool.length + cPool.length + bPool.length];
         System.arraycopy(dPool, 0, pool, 0, dPool.length);
         System.arraycopy(cPool, 0, pool, dPool.length, cPool.length);
         System.arraycopy(bPool, 0, pool, dPool.length + cPool.length, bPool.length);
         return pool;
      } else if (rank.ordinal() >= QuestDefinition.QuestRank.C.ordinal()) {
         TemplateId[] pool = new TemplateId[dPool.length + cPool.length];
         System.arraycopy(dPool, 0, pool, 0, dPool.length);
         System.arraycopy(cPool, 0, pool, dPool.length, cPool.length);
         return pool;
      } else {
         return dPool;
      }
   }

   private static Map<VillageHelper.Village, String> villageDescs(String leaf, String sand, String mist, String stone, String cloud, String rain, String unknown) {
      Map<VillageHelper.Village, String> map = new HashMap();
      map.put(VillageHelper.Village.LEAF, leaf);
      map.put(VillageHelper.Village.SAND, sand);
      map.put(VillageHelper.Village.MIST, mist);
      map.put(VillageHelper.Village.STONE, stone);
      map.put(VillageHelper.Village.CLOUD, cloud);
      map.put(VillageHelper.Village.RAIN, rain);
      map.put(VillageHelper.Village.UNKNOWN, unknown);
      return map;
   }

   public static enum TemplateId {
      DAILY_D_PATROL,
      DAILY_D_GATEGUARD,
      DAILY_D_GENINHUNT,
      DAILY_D_CAMPRAID,
      DAILY_D_BOUNTY,
      DAILY_D_TRAINING_INTRUDER,
      DAILY_D_CARGO,
      DAILY_D_CHECKPOINT,
      WEEKLY_D_INVESTIGATION,
      WEEKLY_D_BORDER,
      WEEKLY_D_SUPPLY,
      WEEKLY_D_HIDEOUT,
      WEEKLY_D_FESTIVAL,
      WEEKLY_D_MISSING_PERSON,
      RANDOM_D_WANDERER,
      RANDOM_D_DUEL,
      RANDOM_D_AMBUSH,
      RANDOM_D_ROGUES,
      RANDOM_D_ESCORT,
      RANDOM_D_CAMP,
      RANDOM_D_TRAP,
      DAILY_C_ESCORT,
      DAILY_C_AMBUSH,
      DAILY_C_ROGUE_DUO,
      DAILY_C_CAMP,
      DAILY_C_BOUNTY,
      DAILY_C_DEFECTOR,
      DAILY_C_SMUGGLER,
      DAILY_C_OUTPOST,
      WEEKLY_C_TRADE_ROUTE,
      WEEKLY_C_INVESTIGATION,
      WEEKLY_C_LIBERATION,
      WEEKLY_C_BORDER,
      WEEKLY_C_INFORMANT,
      WEEKLY_C_HUNTER,
      RANDOM_C_TRAVELER,
      RANDOM_C_BOUNTY,
      RANDOM_C_AMBUSH_DUO,
      RANDOM_C_SWEEP,
      RANDOM_C_ESCORT_CLEAR,
      RANDOM_C_BOUNTY_PAIR,
      RANDOM_C_FIELD_DEFENSE,
      DAILY_B_PATROL,
      DAILY_B_ROGUE_CELL,
      DAILY_B_BOUNTY,
      DAILY_B_AMBUSH,
      DAILY_B_OUTPOST,
      DAILY_B_ESCORT,
      DAILY_B_DEFECTOR,
      DAILY_B_SABOTAGE,
      WEEKLY_B_CRIMINAL_ORG,
      WEEKLY_B_BORDER_INVASION,
      WEEKLY_B_JONIN_HUNT,
      WEEKLY_B_INTEL_NETWORK,
      WEEKLY_B_SIEGE_DEFENSE,
      WEEKLY_B_KAGE_DIRECTIVE,
      RANDOM_B_WANDERER,
      RANDOM_B_BOUNTY,
      RANDOM_B_AMBUSH_TRIO,
      RANDOM_B_SWEEP,
      RANDOM_B_DUO,
      RANDOM_B_CHECKPOINT,
      RANDOM_B_HUNTER;
   }

   public static class StepTemplate {
      public final QuestStep.StepType type;
      public final String descriptionTemplate;
      public final String[] enemyPool;
      public final int enemyCountMin;
      public final int enemyCountMax;
      public final String dialogNpcConfigId;
      public final String[] dialogLineTemplate;
      public final String[] dialogResponseTemplate;
      public final int offsetMinBlocks;
      public final int offsetMaxBlocks;
      public final boolean nearVillage;

      private StepTemplate(QuestStep.StepType type, String descriptionTemplate, String[] enemyPool, int enemyCountMin, int enemyCountMax, String dialogNpcConfigId, String[] dialogLineTemplate, String[] dialogResponseTemplate, int offsetMinBlocks, int offsetMaxBlocks, boolean nearVillage) {
         this.type = type;
         this.descriptionTemplate = descriptionTemplate;
         this.enemyPool = enemyPool;
         this.enemyCountMin = enemyCountMin;
         this.enemyCountMax = enemyCountMax;
         this.dialogNpcConfigId = dialogNpcConfigId;
         this.dialogLineTemplate = dialogLineTemplate;
         this.dialogResponseTemplate = dialogResponseTemplate;
         this.offsetMinBlocks = offsetMinBlocks;
         this.offsetMaxBlocks = offsetMaxBlocks;
         this.nearVillage = nearVillage;
      }

      public static StepTemplate travel(String desc) {
         return new StepTemplate(QuestStep.StepType.TRAVEL, desc, (String[])null, 0, 0, (String)null, (String[])null, (String[])null, 0, 0, false);
      }

      public static StepTemplate travelNearVillage(String desc) {
         return new StepTemplate(QuestStep.StepType.TRAVEL, desc, (String[])null, 0, 0, (String)null, (String[])null, (String[])null, 0, 0, true);
      }

      public static StepTemplate travelOffset(String desc, int minOff, int maxOff) {
         return new StepTemplate(QuestStep.StepType.TRAVEL, desc, (String[])null, 0, 0, (String)null, (String[])null, (String[])null, minOff, maxOff, false);
      }

      public static StepTemplate combat(String desc, String[] pool, int minCount, int maxCount) {
         return new StepTemplate(QuestStep.StepType.COMBAT, desc, pool, minCount, maxCount, (String)null, (String[])null, (String[])null, 0, 0, false);
      }

      public static StepTemplate combatOffset(String desc, String[] pool, int minCount, int maxCount, int minOff, int maxOff) {
         return new StepTemplate(QuestStep.StepType.COMBAT, desc, pool, minCount, maxCount, (String)null, (String[])null, (String[])null, minOff, maxOff, false);
      }

      public static StepTemplate dialogNearVillage(String desc, String npcConfigId, String[] lines, String[] responses) {
         return new StepTemplate(QuestStep.StepType.DIALOG, desc, (String[])null, 0, 0, npcConfigId, lines, responses, 0, 0, true);
      }

      public static StepTemplate dialog(String desc, String npcConfigId, String[] lines, String[] responses) {
         return new StepTemplate(QuestStep.StepType.DIALOG, desc, (String[])null, 0, 0, npcConfigId, lines, responses, 0, 0, false);
      }
   }
}
